/// Embedded YAML rules - compiled into the binary at build time.
/// This ensures ai-rsk works as a standalone binary without needing
/// an external rules/ directory on disk.
///
/// When a rules/ directory IS found on disk (development mode),
/// it takes precedence over these embedded rules.
pub const EMBEDDED_RULES: &[(&str, &str)] = &[
    (
        "bearer-exposed-client.yaml",
        include_str!("../rules/bearer-exposed-client.yaml"),
    ),
    (
        "body-parser-no-limit.yaml",
        include_str!("../rules/body-parser-no-limit.yaml"),
    ),
    (
        "cdn-script-no-sri.yaml",
        include_str!("../rules/cdn-script-no-sri.yaml"),
    ),
    (
        "client-side-auth-only.yaml",
        include_str!("../rules/client-side-auth-only.yaml"),
    ),
    (
        "console-log-sensitive.yaml",
        include_str!("../rules/console-log-sensitive.yaml"),
    ),
    (
        "cors-wildcard.yaml",
        include_str!("../rules/cors-wildcard.yaml"),
    ),
    (
        "dangerouslysetinnerhtml-dynamic.yaml",
        include_str!("../rules/dangerouslysetinnerhtml-dynamic.yaml"),
    ),
    (
        "eval-dynamic.yaml",
        include_str!("../rules/eval-dynamic.yaml"),
    ),
    (
        "hardcoded-secret.yaml",
        include_str!("../rules/hardcoded-secret.yaml"),
    ),
    (
        "jwt-sensitive-payload.yaml",
        include_str!("../rules/jwt-sensitive-payload.yaml"),
    ),
    (
        "missing-csp.yaml",
        include_str!("../rules/missing-csp.yaml"),
    ),
    (
        "missing-hsts.yaml",
        include_str!("../rules/missing-hsts.yaml"),
    ),
    (
        "missing-httponly.yaml",
        include_str!("../rules/missing-httponly.yaml"),
    ),
    (
        "missing-rate-limit.yaml",
        include_str!("../rules/missing-rate-limit.yaml"),
    ),
    (
        "missing-samesite.yaml",
        include_str!("../rules/missing-samesite.yaml"),
    ),
    (
        "missing-secure-cookie.yaml",
        include_str!("../rules/missing-secure-cookie.yaml"),
    ),
    (
        "missing-xcontent-type.yaml",
        include_str!("../rules/missing-xcontent-type.yaml"),
    ),
    (
        "missing-xframe.yaml",
        include_str!("../rules/missing-xframe.yaml"),
    ),
    (
        "negative-business-value.yaml",
        include_str!("../rules/negative-business-value.yaml"),
    ),
    ("no-helmet.yaml", include_str!("../rules/no-helmet.yaml")),
    (
        "postmessage-no-origin.yaml",
        include_str!("../rules/postmessage-no-origin.yaml"),
    ),
    (
        "prompt-injection-concat.yaml",
        include_str!("../rules/prompt-injection-concat.yaml"),
    ),
    (
        "select-star-response.yaml",
        include_str!("../rules/select-star-response.yaml"),
    ),
    (
        "source-maps-in-prod.yaml",
        include_str!("../rules/source-maps-in-prod.yaml"),
    ),
    (
        "ssrf-dynamic-fetch.yaml",
        include_str!("../rules/ssrf-dynamic-fetch.yaml"),
    ),
    (
        "stripe-no-webhook-verify.yaml",
        include_str!("../rules/stripe-no-webhook-verify.yaml"),
    ),
    (
        "token-in-localstorage.yaml",
        include_str!("../rules/token-in-localstorage.yaml"),
    ),
    (
        "unvalidated-redirect.yaml",
        include_str!("../rules/unvalidated-redirect.yaml"),
    ),
    (
        "websocket-no-auth.yaml",
        include_str!("../rules/websocket-no-auth.yaml"),
    ),
    (
        "window-opener-no-noopener.yaml",
        include_str!("../rules/window-opener-no-noopener.yaml"),
    ),
    (
        "xpoweredby-exposed.yaml",
        include_str!("../rules/xpoweredby-exposed.yaml"),
    ),
];
